### ISSUE TITLE
Crash on kodi V17.0

### ISSUE THREAD

**Issue by vlsinitsyn** [matthuisman/plugin.video.nz.freeview#1]
The plugin IPtv nz V 0.13.5 is crashing when staring on Kodi 17.0 with the following error:
AttributeError: 'xbmcgai.ListItem' object has no attribute 'getPath'
File plugin.py line 176, in display
File plugin.py line 42, in decorated_function item.display()
File router.py linee 77 in dispatch function (**params)

**Comment by matthuisman** [comment]
Try newer kodi. Eg 17.2 or 18.1

**Comment by matthuisman** [comment]
I've just pushed 0.13.8 that removes all calls to "getPath".
So should work on older Kodi versions now
