### ISSUE TITLE
Etv Freeview 

### ISSUE THREAD

**Issue by hidemyassbaby** [matthuisman/plugin.video.nz.freeview#2]
Hopefully you can break security on this site etv they have full freeview incl prime

http://www.etv.org.nz/

Login as organisation

@auckland.ac.nz

It will redirect you to sign in page use this

p1775348@mvrht.com

Password 

prelude16

Has nz catchup docs and nz freeview (fully non geoblocked)

Possibly you could code and make a kodi addon ETV also

I found a away to get free Logins with out needing to be at a polytechnic or university and that was via signing up at Auckland University on there site

**Comment by matthuisman** [comment]
This is already known.
I only use public free streams for my IPTV stuff.
I could look into an ETV add-on though where you login and then access the streams that way.

**Comment by hidemyassbaby** [comment]
A ETV addon would be amaing
