### ISSUE TITLE
Issue with TVNZ 1

### ISSUE THREAD

**Issue by AndrewLugg** [matthuisman/plugin.video.nz.freeview#3]
This stream seems to be broken https://i.mjh.nz/nz/tv.9.m3u8 it is returning 500

I checked the path of the stream on tvnz and it states: https://d2ce82tpc3p734.cloudfront.net/v1/manifest/b1f4432f8f95be9e629d97baabfed15b8cacd1f8/TVNZ_1/7856e20e-d15f-436c-8815-6b03008b66af/2.m3u8

But your one links to:
https://d2ce82tpc3p734.cloudfront.net/v1/master/b1f4432f8f95be9e629d97baabfed15b8cacd1f8/TVNZ_1/../../../manifest/b1f4432f8f95be9e629d97baabfed15b8cacd1f8/TVNZ_1/c4b8175f-1018-418b-bae8-f02307e4c5b3/4.m3u8

**Comment by matthuisman** [comment]
Your in New Zealand?

**Comment by AndrewLugg** [comment]
Yep, I tried it through Plex, where I normally use IPTV, but I tried the links in VLC as well, and it gets a 500, when I replace that link with the one from https://www.tvnz.co.nz/livetv it works in both VLC and Plex,

**Comment by matthuisman** [comment]
should be fixed now :)
